ECHO Git init file generated by UE4_git.py
git init
git add git_add.bat
git add init_git_UE4.bat
git add sanct_all_files.csv
git add sanct_git_files.csv
git add sanct_missed_files.csv
git commit -m "initial setup of sanct"
git remote add origin https://github.com/acutesoftware/UE4_sanct

ECHO you may want the following commands as well:
ECHO    git pull origin master
ECHO    git push --set-upstream origin master

