#!/usr/bin/python3
# coding: utf-8
# fue.py
# uses the full filelist generated by "create_ue4_filelist.py" to
# find project details, individual assets or packages

import os 
import sys 

pth = r'E:\UE4_proj'
search_file = 'files_ue4.txt'

def main():
    srch_term = ' '.join(sys.argv[1:])
    raw_results = find_strings(srch_term)
    for raw_result in raw_results:
        print(get_short_name(raw_result))

    print('found ' + str(len(raw_results)) + ' results for ' + srch_term)

def find_strings(raw_srch_term):
    raw = []
    srch_terms = raw_srch_term.upper().split(' ')
    num_terms = len(srch_terms)
    print(srch_terms)
    with open(search_file, 'r') as fip:
        for line in fip:
            found = 0
            for srch_term in srch_terms:
                if srch_term in line.upper():
                    found += 1
                    #print('srch_term[0:1] = ', srch_term[0:1])
                    if srch_term[0:1] == '-':
                        print('srch_term[1:]', srch_term[1:])
                        if srch_term[1:] in line.upper():
                            print('excluding ' + srch_term[1:])
                            found = -99


            if found == num_terms:
                raw.append(line)
    return raw

def get_short_name(raw_result):
    """
    parses a CSV line from search file to get a nice UE4 friendly name
    """
    cols = raw_result.split(',')
    res = cols[1][1:][:-1] + ' (' + cols[3][1:][:-1] + ') in folder ' + cols[2][1:][:-1]
    return res


if __name__ == '__main__':  
    if len(sys.argv) < 2:
        print("fue.py - Find UE4 files, packages, assets\n")
        print("uses the full filelist generated by create_ue4_filelist.py to")
        print("find project details.\n")
        print("usage:\n     python .\\fue.py search_terms (space separated)\n")
        print("example:")
        print("     python .\\fue.py lvl_ 2021-01  # find all levels modified in October 2021")
        print("     python .\\fue.py _djm craft \\sanct\\  # find crafting assets in main djm folder in sanct projects")
        print("     python .\\fue.py _djm craft \\sanct\\ \\Textures\\  # find textures for crafting assets in main djm folder in sanct projects")
        print("     python .\\fue.py _djm craft \\sanct\\ -.png # find crafting assets same folder but exclude png files")
        print("")
        exit(1)
    main()            